global:
  imagePullPolicy: Always
  environment: production


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  backendService:
    port: 8080
  ingress:
    host: front-lspiridonov.2sem.students-projects.ru
    path: /
    pathType: Prefix
    tlsSecretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: lspiridonov/sausage-frontend:latest
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    vaultEnabled: "false"
    vaultHealthEnabled: "false"
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    mongoUri: mongodb://reports:reportspassword@mongodb:27017/sausage-store?authSource=sausage-store
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  image: lspiridonov/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: backend
          controlledResources:
            - cpu
            - memory

backend-report:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  image: lspiridonov/sausage-backend-report:latest
  containerPort: 8080
  service:
    port: 8080
  config:
    port: "8080"
  secret:
    db: mongodb://reports:reportspassword@mongodb:27017/sausage-store?authSource=sausage-store
  resources:
    requests:
      memory: "64Mi"
      cpu: "75m"
    limits:
      memory: "192Mi"
      cpu: "250m"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    averageUtilization: 75

infra:
  postgresql:
    image: postgres:16-alpine
    containerPort: 5432
    service:
      port: 5432
    database: sausage-store
    username: store
    password: storepassword
    storage: 1Gi
    resources:
      requests:
        memory: "96Mi"
        cpu: "100m"
      limits:
        memory: "384Mi"
        cpu: "350m"
  mongodb:
    image: mongo:7.0
    rootUsername: root
    rootPassword: rootpassword
    database: sausage-store
    reportsUsername: reports
    reportsPassword: reportspassword
    containerPort: 27017
    service:
      port: 27017
    storage: 1Gi
    resources:
      requests:
        memory: "96Mi"
        cpu: "100m"
      limits:
        memory: "384Mi"
        cpu: "350m"
