---
apiVersion: v1
kind: Service
metadata:
  name: { { printf "%s-%s-service" .Release.Name .Chart.Name | quote } }
  labels:
    app.kubernetes.io/name: { { .Chart.Name | quote } }
    app.kubernetes.io/instance: { { .Release.Name | quote } }
    app.kubernetes.io/version: { { .Chart.AppVersion | quote } }
    app.kubernetes.io/managed-by: { { .Release.Service | quote } }
    helm.sh/chart: { { printf "%s-%s" .Chart.Name .Chart.Version | quote } }
    app.kubernetes.io/component: { { .Chart.Name | quote } }
    app.kubernetes.io/part-of: "sausage-store"
    env: { { .Values.global.environment | quote } }
spec:
  type: ClusterIP
  ports:
    - name: http
      port: { { .Values.service.port } }
      protocol: TCP
      targetPort: { { .Values.containerPort } }
  selector:
    app: { { printf "%s-%s" .Release.Name .Chart.Name | quote } }
